### ISSUE TITLE
Queued downloads?

### ISSUE THREAD

**Issue by Dokman** [qtoncoding/CrunchyRollLiveStreamer#1]
Can you make a queue for the downloads, the people we have bad internet can't handle all the file downloading in the same time :(

**Comment by qtoncoding** [comment]
Agree, I'll put in a change for this soon.

**Comment by Dokman** [comment]
so for example you can get the number of episodes and then query it one by one

**Comment by qtoncoding** [comment]
https://github.com/qtoncoding/CrunchyRollLiveStreamer/commit/4c066e3d7ba2aab15ad172e096b9278152fc6103

This commit adds the UI for Queue Download. 
Functionality will come in a later commit.

**Comment by qtoncoding** [comment]
https://github.com/qtoncoding/CrunchyRollLiveStreamer/commit/f174213ff4cfef3e21e5c9fc1260f776283447ec

Queue is now implemented.
A maximum downloads going on at the same time can be specified.
Queue will work on selected episodes, or on all episodes if none is selected.
